apiVersion: skaffold/v2beta29
kind: Config
metadata:
  name: skaffold-eks
build:
  tagPolicy:
    sha256: {}
  artifacts:
  - image: quay.io/shardul/skaffold-example
deploy:
  kubectl:
    manifests:
      - manifests/k8s-pod.yaml
